# This is a basic workflow to help you get started with Actions
name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: requirements
        run: |
          npm install &&\
          npm install -g @angular/cli@7.1.3 &&\
          pip install transifex-client
      - name: git identity
        run: |
          git config user.email "adam.kariv@gmail.com"
          git config user.name "Adam Kariv"
      - name: transifex
        env:
          TX_TOKEN: ${{ secrets.REPORTIT_TRANSIFEX_TOKEN }}
        run: |
          . extract_i18n.sh
          tx push --source
          tx pull --mode sourceastranslation -l ar,en,am,ru
      - name: build
        run: |
          git checkout master && \
          (git branch -D dist || true) && \
          git checkout -b dist && \
          rm .gitignore && \
          ng build --prod -c production && \
          ng build --prod -c ar && \
          ng build --prod -c en && \
          ng build --prod -c ru && \
          ng build --prod -c am && \
          cp CNAME dist/reportit-user/
      - name: deploy
        run: |
          git add dist/reportit-user && \
          git commit -m dist && \
          (git branch -D gh-pages || true) && \
          git subtree split --prefix dist/reportit-user -b gh-pages && \
          git push -f origin gh-pages:gh-pages && \
          git checkout master && \
          git branch -D gh-pages && \
          git branch -D dist && \
          git checkout . && \
          git push
